Vagrant.configure("2") do |config|
  config.vm.box = "precise64"

    config.vm.define :web1 do |cfg|
        cfg.vm.network :private_network, ip: "172.20.30.10"
        cfg.vm.provider :virtualbox do |v|
            v.name = "web1"
        end
    end

    config.vm.define :db1 do |cfg|
        cfg.vm.network :private_network, ip: "172.20.30.11"
        cfg.vm.provider :virtualbox do |v|
            v.name = "db1"
	end
end

        config.vm.provision :ansible do |ansible|
          ansible.playbook = "site.yml"
          ansible.inventory_path = "vagrant_hosts"
#          ansible.sudo = "true"
   	end
end
